#!/bin/bash

if [ $# -ne 3 ]; then
    echo -e "Help:\n\t$0 alias remote_source local_destination"
    exit 1
fi    

# Get the command
cmd=$(htool rsync $1)
rval=$?

if [ $rval -eq 0 ]; then
    shift
    rsync -avzLP "$cmd":$1 $2
else
    echo $cmd
fi
